name: test-linux

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: docker build -f test/Dockerfile -t csgo-dof-screenshot-test .
      - run: docker run --rm csgo-dof-screenshot-test
